import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { AppCard, Chip, IconButton, palette, PrimaryButton, SectionHeader } from "@/components/app/ui";
import { calcSessionMinutes, calcSessionVolume } from "@/features/analytics";
import { useFitness } from "@/context/fitness-context";

export default function SessionDetailScreen() {
  const router = useRouter();
  const params = useLocalSearchParams<{ id: string }>();
  const { database } = useFitness();
  const session = database.sessions.find((item) => item.id === params.id);
  if (!session) return <View style={styles.notFound}><Text style={styles.notFoundText}>Sesión no encontrada.</Text><PrimaryButton label="Volver" variant="ghost" icon="arrow-back" onPress={() => router.back()} /></View>;
  const date = new Intl.DateTimeFormat("es-ES", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date(session.scheduledDate));
  return <View style={styles.screen}><View style={styles.header}><IconButton icon="arrow-back" label="Volver" onPress={() => router.back()} /><Text style={styles.headerTitle}>Detalle de sesión</Text><View style={styles.spacer} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View><Chip label="HISTORIAL" tone="blue" /><Text style={styles.title}>{session.trainingDayName}</Text><Text style={styles.date}>{date}</Text></View><AppCard><View style={styles.metrics}><View><Text style={styles.metricLabel}>VOLUMEN</Text><Text style={styles.metricValue}>{Math.round(calcSessionVolume(session)).toLocaleString("es-ES")} kg</Text></View><View style={styles.verticalDivider} /><View><Text style={styles.metricLabel}>DURACIÓN</Text><Text style={styles.metricValue}>{calcSessionMinutes(session)} min</Text></View></View><View style={styles.metaRow}>{session.block ? <Chip label={session.block} /> : null}{session.mesocycle ? <Chip label={session.mesocycle} tone="blue" /> : null}<Chip label="COMPLETADA" tone="success" /></View></AppCard><SectionHeader title="Lo que realizaste" />{session.exercises.map((exercise) => <AppCard key={exercise.id} style={styles.exerciseCard}><View style={styles.exerciseHead}><View><Text style={styles.exerciseName}>{exercise.name}</Text><Text style={styles.exerciseTarget}>Objetivo: {exercise.target.sets} × {exercise.target.repRangeMin}–{exercise.target.repRangeMax}</Text></View><Chip label={`${exercise.sets.length} series`} /></View><View style={styles.sets}>{exercise.sets.map((set) => <View key={set.id} style={styles.setLine}><Text style={styles.setOrder}>S{set.order}</Text><Text style={styles.setValue}>{set.weight} kg × {set.reps}</Text><Text style={styles.setRir}>{set.rir !== undefined ? `RIR ${set.rir}` : set.rpe !== undefined ? `RPE ${set.rpe}` : ""}</Text></View>)}</View></AppCard>)}{session.notes ? <AppCard style={styles.notes}><MaterialIcons name="notes" size={18} color={palette.blue} /><View style={styles.notesText}><Text style={styles.noteLabel}>CONCLUSIONES</Text><Text style={styles.noteCopy}>{session.notes}</Text></View></AppCard> : null}</ScrollView></View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: palette.bg }, notFound: { flex: 1, backgroundColor: palette.bg, justifyContent: "center", padding: 24, gap: 18 }, notFoundText: { color: palette.text, fontSize: 18, fontWeight: "900", textAlign: "center" }, header: { height: 70, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderColor: palette.border }, headerTitle: { color: palette.text, fontWeight: "900", fontSize: 15 }, spacer: { width: 40 }, content: { padding: 18, paddingBottom: 35, gap: 13 }, title: { color: palette.text, fontSize: 29, fontWeight: "900", letterSpacing: -0.8, marginTop: 12, textTransform: "capitalize" }, date: { color: palette.muted, fontSize: 13, marginTop: 4, textTransform: "capitalize" }, metrics: { flexDirection: "row", alignItems: "center" }, metricLabel: { color: palette.muted, fontSize: 10, fontWeight: "900", letterSpacing: 0.7 }, metricValue: { color: palette.lime, fontSize: 19, fontWeight: "900", marginTop: 4 }, verticalDivider: { height: 35, width: 1, backgroundColor: palette.border, marginHorizontal: 25 }, metaRow: { flexDirection: "row", gap: 7, marginTop: 16, flexWrap: "wrap" }, exerciseCard: { gap: 13 }, exerciseHead: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 }, exerciseName: { color: palette.text, fontSize: 15, fontWeight: "900" }, exerciseTarget: { color: palette.muted, fontSize: 11, marginTop: 3 }, sets: { gap: 7 }, setLine: { flexDirection: "row", alignItems: "center", paddingVertical: 9, paddingHorizontal: 10, borderRadius: 11, backgroundColor: palette.surfaceAlt }, setOrder: { width: 35, color: palette.muted, fontSize: 12, fontWeight: "900" }, setValue: { flex: 1, color: palette.text, fontSize: 14, fontWeight: "800" }, setRir: { color: palette.lime, fontSize: 11, fontWeight: "800" }, notes: { flexDirection: "row", gap: 10, backgroundColor: palette.blueSoft, borderColor: "#214D68" }, notesText: { flex: 1 }, noteLabel: { color: palette.blue, fontSize: 10, fontWeight: "900", letterSpacing: 0.7 }, noteCopy: { color: palette.text, fontSize: 13, lineHeight: 19, marginTop: 4 },
});
