import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppCard, Chip, IconButton, palette, PrimaryButton } from "@/components/app/ui";
import { useFitness } from "@/context/fitness-context";
import { dayNames } from "@/types/fitness";

const iso = (date: Date) => date.toISOString().slice(0, 10);

export default function CalendarScreen() {
  const router = useRouter();
  const { database, activeRoutine, startWorkout } = useFitness();
  const [year, month] = [new Date().getFullYear(), new Date().getMonth()];
  const first = new Date(year, month, 1); const days = new Date(year, month + 1, 0).getDate();
  const leading = (first.getDay() + 6) % 7;
  const cells = [...Array(leading).fill(null), ...Array.from({ length: days }, (_, index) => index + 1)];
  const monthLabel = new Intl.DateTimeFormat("es-ES", { month: "long", year: "numeric" }).format(new Date(year, month, 1));
  const sessionFor = (date: string) => database.sessions.find((session) => session.scheduledDate === date);
  const routineDayFor = (date: Date) => activeRoutine?.trainingDays.find((day) => day.weekday === date.getDay());

  return <View style={styles.screen}><View style={styles.header}><IconButton icon="arrow-back" label="Volver" onPress={() => router.back()} /><View style={styles.headerCenter}><Text style={styles.headerTitle}>Calendario</Text><Text style={styles.headerSubtitle}>Tu semana de un vistazo</Text></View><View style={styles.spacer} /></View><ScrollView contentContainerStyle={styles.content}><AppCard><View style={styles.monthHeader}><Text style={styles.monthTitle}>{monthLabel}</Text><View style={styles.monthArrows}><MaterialIcons name="chevron-left" size={20} color={palette.muted} /><MaterialIcons name="chevron-right" size={20} color={palette.muted} /></View></View><View style={styles.weekRow}>{dayNames.slice(1).concat(dayNames[0]).map((day) => <Text key={day} style={styles.weekLabel}>{day.slice(0, 1)}</Text>)}</View><View style={styles.grid}>{cells.map((day, index) => { if (!day) return <View key={`empty-${index}`} style={styles.cell} />; const date = iso(new Date(year, month, day)); const session = sessionFor(date); const trainingDay = routineDayFor(new Date(year, month, day)); const state = session?.status === "completed" ? "completed" : session?.status === "skipped" ? "skipped" : trainingDay ? "scheduled" : "rest"; return <Pressable key={date} onPress={async () => { if (session) { router.push({ pathname: "/session/[id]", params: { id: session.id } } as never); } else if (trainingDay) { const id = await startWorkout(trainingDay.id); if (id) router.push({ pathname: "/workout/[id]", params: { id } } as never); } }} style={({ pressed }) => [styles.cell, pressed && styles.pressed]}><Text style={[styles.dayNumber, state === "completed" && styles.dayCompleted, state === "scheduled" && styles.dayScheduled]}>{day}</Text><View style={[styles.stateDot, state === "completed" && styles.dotCompleted, state === "scheduled" && styles.dotScheduled, state === "skipped" && styles.dotSkipped]} /></Pressable>; })}</View></AppCard><View style={styles.legend}>{[["completed", "Completado"], ["scheduled", "Programado"], ["rest", "Descanso"], ["skipped", "Omitido"]].map(([state, label]) => <View key={state} style={styles.legendItem}><View style={[styles.legendDot, state === "completed" && styles.dotCompleted, state === "scheduled" && styles.dotScheduled, state === "skipped" && styles.dotSkipped]} /><Text style={styles.legendText}>{label}</Text></View>)}</View><AppCard style={styles.info}><MaterialIcons name="event-note" size={20} color={palette.blue} /><View style={styles.infoText}><Text style={styles.infoTitle}>Selecciona un día</Text><Text style={styles.infoCopy}>Los días programados abren directamente el modo entrenamiento. Los completados muestran su historial.</Text></View></AppCard><PrimaryButton label="Volver al inicio" icon="home" variant="ghost" onPress={() => router.replace("/(tabs)" as never)} /></ScrollView></View>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.bg }, header: { height: 70, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderColor: palette.border }, headerCenter: { alignItems: "center" }, headerTitle: { color: palette.text, fontSize: 15, fontWeight: "900" }, headerSubtitle: { color: palette.muted, fontSize: 10, marginTop: 2 }, spacer: { width: 40 }, content: { padding: 18, paddingBottom: 34, gap: 14 }, monthHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }, monthTitle: { color: palette.text, fontSize: 18, fontWeight: "900", textTransform: "capitalize" }, monthArrows: { flexDirection: "row", gap: 14 }, weekRow: { flexDirection: "row", justifyContent: "space-around", marginBottom: 9 }, weekLabel: { color: palette.muted, fontSize: 11, fontWeight: "900", width: "14.28%", textAlign: "center" }, grid: { flexDirection: "row", flexWrap: "wrap" }, cell: { width: "14.28%", aspectRatio: 0.9, alignItems: "center", justifyContent: "center", gap: 4 }, dayNumber: { color: palette.muted, fontSize: 14, fontWeight: "800", height: 29, width: 29, textAlign: "center", paddingTop: 6, borderRadius: 10 }, dayCompleted: { color: palette.bg, backgroundColor: palette.lime }, dayScheduled: { color: palette.blue, backgroundColor: palette.blueSoft }, stateDot: { height: 4, width: 4, borderRadius: 2, backgroundColor: palette.border }, dotCompleted: { backgroundColor: palette.lime }, dotScheduled: { backgroundColor: palette.blue }, dotSkipped: { backgroundColor: palette.danger }, legend: { flexDirection: "row", flexWrap: "wrap", gap: 12 }, legendItem: { flexDirection: "row", alignItems: "center", gap: 5 }, legendDot: { height: 7, width: 7, borderRadius: 4, backgroundColor: palette.border }, legendText: { color: palette.muted, fontSize: 11 }, info: { flexDirection: "row", gap: 10, backgroundColor: palette.blueSoft, borderColor: "#214D68" }, infoText: { flex: 1 }, infoTitle: { color: palette.blue, fontWeight: "900", fontSize: 13 }, infoCopy: { color: "#BBDFF4", fontSize: 11, lineHeight: 16, marginTop: 3 }, pressed: { opacity: 0.7 } });
