import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppCard, AppInput, Chip, IconButton, palette, PrimaryButton, SectionHeader } from "@/components/app/ui";
import { useFitness } from "@/context/fitness-context";

export default function RecordsScreen() {
  const router = useRouter();
  const { database, addManualRecord } = useFitness();
  const [selectedId, setSelectedId] = useState(database.exercises[0]?.id ?? "");
  const [weight, setWeight] = useState("");
  const [reps, setReps] = useState("");
  const selected = database.exercises.find((exercise) => exercise.id === selectedId);
  const save = async () => {
    const kg = Number(weight.replace(",", ".")); const count = Number(reps);
    if (!selected || !Number.isFinite(kg) || kg <= 0 || !Number.isInteger(count) || count <= 0) { Alert.alert("Revisa la marca", "Indica un ejercicio, peso mayor que cero y repeticiones válidas."); return; }
    await addManualRecord({ exerciseId: selected.id, exerciseName: selected.name, date: new Date().toISOString().slice(0, 10), weight: kg, reps: count, type: "weight" });
    setWeight(""); setReps("");
    Alert.alert("Marca guardada", `${selected.name}: ${kg} kg × ${count} reps`);
  };
  return <View style={styles.screen}><View style={styles.header}><IconButton icon="arrow-back" label="Volver" onPress={() => router.back()} /><View style={styles.headerCenter}><Text style={styles.headerTitle}>Rendimientos máximos</Text><Text style={styles.headerSubtitle}>Registra o consulta tus PRs</Text></View><View style={styles.spacer} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><AppCard style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="emoji-events" size={26} color={palette.warning} /></View><View><Text style={styles.heroTitle}>Nueva marca manual</Text><Text style={styles.heroCopy}>No dependas exclusivamente del 1RM: guarda el rendimiento que importa para ti.</Text></View></AppCard><SectionHeader title="Ejercicio" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.exerciseChoices}>{database.exercises.map((exercise) => <Pressable key={exercise.id} onPress={() => setSelectedId(exercise.id)} style={({ pressed }) => [styles.exerciseChoice, selectedId === exercise.id && styles.exerciseChoiceActive, pressed && styles.pressed]}><Text style={[styles.exerciseChoiceText, selectedId === exercise.id && styles.exerciseChoiceTextActive]}>{exercise.name}</Text></Pressable>)}</ScrollView><SectionHeader title="Rendimiento" /><View style={styles.fields}><AppInput label="Peso (kg)" placeholder="120" value={weight} onChangeText={setWeight} keyboardType="decimal-pad" /><AppInput label="Repeticiones" placeholder="5" value={reps} onChangeText={setReps} keyboardType="number-pad" /></View><PrimaryButton label="Guardar rendimiento" icon="emoji-events" onPress={() => void save()} /><SectionHeader title="Historial de marcas" />{database.records.sort((a, b) => b.date.localeCompare(a.date)).map((record) => <AppCard key={record.id} style={styles.record}><View style={styles.recordIcon}><MaterialIcons name="emoji-events" size={18} color={palette.warning} /></View><View style={styles.recordText}><Text style={styles.recordName}>{record.exerciseName}</Text><Text style={styles.recordMeta}>{new Intl.DateTimeFormat("es-ES", { day: "numeric", month: "short" }).format(new Date(record.date))} · {record.type === "weight" ? "Mejor carga" : "Rendimiento estimado"}</Text></View><Text style={styles.recordValue}>{record.weight} × {record.reps}</Text></AppCard>)}</ScrollView></View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: palette.bg }, header: { height: 70, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderColor: palette.border }, headerCenter: { alignItems: "center" }, headerTitle: { color: palette.text, fontWeight: "900", fontSize: 15 }, headerSubtitle: { color: palette.muted, fontSize: 10, marginTop: 2 }, spacer: { width: 40 }, content: { padding: 18, paddingBottom: 34, gap: 13 }, hero: { flexDirection: "row", gap: 12, backgroundColor: "#2B2615", borderColor: "#5E4C1A" }, heroIcon: { height: 46, width: 46, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#473816" }, heroTitle: { color: palette.warning, fontSize: 15, fontWeight: "900" }, heroCopy: { color: "#D7CA9B", fontSize: 12, lineHeight: 17, marginTop: 4, paddingRight: 15 }, exerciseChoices: { gap: 8, paddingRight: 18 }, exerciseChoice: { backgroundColor: palette.surface, borderColor: palette.border, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 12 }, exerciseChoiceActive: { borderColor: palette.lime, backgroundColor: palette.limeSoft }, exerciseChoiceText: { color: palette.muted, fontWeight: "800", fontSize: 12 }, exerciseChoiceTextActive: { color: palette.lime }, fields: { gap: 11 }, record: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 12 }, recordIcon: { height: 34, width: 34, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "#3D3013" }, recordText: { flex: 1 }, recordName: { color: palette.text, fontWeight: "800", fontSize: 13 }, recordMeta: { color: palette.muted, fontSize: 11, marginTop: 3 }, recordValue: { color: palette.lime, fontSize: 15, fontWeight: "900" }, pressed: { opacity: 0.72 },
});
